### ISSUE TITLE
Style setting request: toggle to not hide buttons on the side bar

### ISSUE THREAD

**Issue by gortium** [kinmury/GoldenCoffeeTheme#2]
I would like the option to toggle not to hide buttons on the side bar. On mobile having them hiden is really painfull.

**Comment by kinmury** [comment]
I added the "Style Setting" setting so you can toggle it :D

Just so you know, I usually don't use Obsidian Mobile as often as I do on the Computer, so it's bound to be a lot of issues on the Mobile Version. I'll try my best to fix Mobile issues, but I'm not sure enough that I'll fix everything. 

I'll appreciate if this issues where posted here, so I know they exist.

And one more thing. Now, since I'm done with the making and release of the "Golden Book" theme, I'll go back to the "Golden Coffee" and start making a mini-rework, since now I gain a little more of CSS experience and now I see all the problems that the "Golden Coffee" theme has (and the lack of the main "Style Settings" settings it has).

So, if you find anything that isn't working good or something that you might think it would look better if I added it to the theme, I'm more than happy to hear it.

Thank you for your contribution, I really appreciate it :D
