### ISSUE TITLE
Buttons sans contrast

### ISSUE THREAD

**Issue by DrorHarari** [kinmury/GoldenCoffeeTheme#4]
Hi @kinmury - thanks for the great theme. I am legally blind (can't see much) and this GoldenCoffe theme was the best one I could find for my condition. There's one annoyance which you might be able to help solve and is shown in the picture below:

![image](https://user-images.githubusercontent.com/1831901/159152518-501f2c81-63ad-4a60-b802-5ead9bd0999d.png)

The "Delete" and "Delete and don't ask again" buttons are totally unreadable. If you can fix that, it would be great.

/d

**Comment by kinmury** [comment]
Amm... Hiii.... I know that I haven't done anything regarding this issue and haven't been active since a long time. I've been busy with my studies. 

Yes, I could've fixed this this issue without much trouble, but as I said before, I haven't had much free time for me to check and fix issue. I'm sorry for the poor time management that I had at that time, but I couldn't do more.

Since I've uploaded a new theme, where I have combined all the preview theme that I've made, please go and check it out. I remember that I fixed this exact issue and more that where similar to this. I hope that the newer version suits you as well as this one. 

Thank you for your time, and I hope you like the new theme (and the updated version of _Golden Coffee_).

**Comment by DrorHarari** [comment]
No worries @kinmury - I also have open source projects and not much time for maintenance... Will check your other theme.

Thanks!
