### ISSUE TITLE
Vietnamese font error

### ISSUE THREAD

**Issue by Mea94** [kinmury/GoldenCoffeeTheme#5]
Hi kinmury, 
I love your theme but is not going well in my language, which is vietnamese. Can you fix this issues? You can see the problem in the picture here ! 
![B22D38EF-1F22-4F6E-AE4F-E6F48653E2D0](https://user-images.githubusercontent.com/103870710/163700542-8f9b71b1-51c6-4406-8dc3-1c34923d44c0.jpeg)

**Comment by kinmury** [comment]
Amm... Hiii.... I know that I haven't done anything regarding this issue and haven't been active since a long time. I've been busy with my studies. 

Regarding this issue, I'm not sure how to fix it. Maybe the problem is in the font that I used or the keyword settings that you use on your computer. I'm really not sure where is the issue, so for now I can't help you.

As of today, I launched my new theme **Ukiyo**, where I combined all my preview themes. I would suggest you to try to use that theme and see how it goes. If the issue still persist, create the issue there and well talk about what is the cause so that I can see how to fix it.

Thank you for your time, and I hope you like the new theme (and the updated version of _Golden Coffee_).
